services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - nodejs-backend-server
  nodejs-backend-server:
    depends_on:
      - postgres_db
  postgres_db:
    container_name: postgres_db
    image: postgres:16.8
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
